language: python
python:
- 2.7
- 3.6
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
install:
- pip install -U pip pip-tools
- pip install numpy scipy scikit-learn
script:
- python setup.py test
notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: 4OJohlirY2EDuf8Acw1lRZ8E/3wKUjQv7owoOPDKoHVkCfYVb654FWoU6A7G6+RfSkdS6mgoSUswg4E8OoLef3BtncdE+9PcijSrq+PbG0D9GQNXB65LnZKHhQTtx/GVUmyH4ooLn3D+qUKnhziPcoxX68h7I5UarHbkmb7eKkQULGAnXvb7hKyLZ/ZdSUq2gPWxTI+LizbjYt3Ccf5TdyLH3xTx5nhduNuUm0HcdIK6BKVEzs4mw9AADXgVTFhlq7JxN4bjmvn4DZgLCB9SvgsvIB89flY+TE2QNi9TwYPteyznoXlbmFrL1LHl65m2wIK8CUCroKeayPZXr7AV+Px10ERMbmnoeIEq855r/vEzhjCJ58rUVjEezsDqu3DAkLw3kMNGLu/xVGZ8OAbPZlzODAokwfAXj6elG5bjSAgnV+mCajTFCEBxYjhNF5BmiBDlPJ4Jz2HNWLhcZyDRFqWFw0ZxYHVmeS/PbdnnrjirxE/Rc6oapogMzZP4wmZPhYZ2+pN7DVSL3LFm830KSKby6NeUoJRXQQlyvxtzBS+uFHKZA9kWQjkQIvJj1hqm2r3ujkX3riaTvHFw9suiUuKSsr/x2gRy1B7jkSQ1ZQN4gi69k84m1NgVGktF54DbaAbUJ0DzSwJMaeyNnwYObCdxyOjHhP1tOVY+fnm6qHM=
